name: commonplace_book
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_speed_dial: ^7.0.0
  get_it: ^8.0.3
  intl: ^0.20.2
  logger: ^2.5.0
  path: ^1.9.0
  path_provider: ^2.1.5
  pie_menu: ^3.2.7
  sqflite: ^2.4.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
